@startgantt planning
' project settings
title duty drawback planning
printscale weekly zoom 3
Project starts the 2021-06-14

' line indicators
today is 2021-10-10 and is colored in blue
2021-10-03 to 2021-10-03 are colored in green

' phase 1
' team 1
[UAT +  fix findings] starts 2021-08-16 and lasts 10 weeks and is 80% complete

[setup development env + submitOrder mode=Final] lasts 3 weeks
    then [process pickup (TXT) data from kafka topic] lasts 1 weeks
    then [process manifest (XML) file from Kafka topic] lasts 1 weeks
    then [call updateTransportInformation] lasts 1 weeks

[submitOrder mode=basic ] starts 2021-08-02 and lasts 1 week

[hyperledger block events] starts 2021-07-26 and lasts 3 weeks and is 100% complete
    then [hyperledger contract events] lasts 2 week and is 100% complete and is colored in red

[amending declaration] starts 2021-08-09 and lasts 3 weeks and is 100% complete
[amending declaration] is colored in LightGreen

[locked-by ] starts 2021-08-16 and lasts 2 weeks and is 100% complete
[locked-by ] is colored in red

[configurable grids (ag-grid)] starts 2021-08-16 and lasts 3 weeks and is 100% complete
[configurable grids (ag-grid)] is colored in red

[submitOrder mode=return] starts 2021-08-30 and lasts 2 weeks and is 100% complete

[submitOrder mode=canceled] starts 2021-08-30 and lasts 3 weeks and is 100% complete
    
[user managment] starts 2021-09-06 and lasts 3 weeks and is 100% complete

[Order validation] starts 2021-09-13 and lasts 2 weeks and is 100% complete 
[Order validation] is colored in red

[confirm return API] starts 2021-09-13 and lasts 3 weeks and is 100% complete 
[confirm return API] is colored in red

[claims] starts 2021-09-13 and lasts 3 weeks and is 100% complete

[retry on status  500] starts 2021-09-20 and lasts 2 weeks and is 100% complete
[retry on status  500] is colored in red

' [chain events] starts 2021-10-4 and lasts 1 weeks and is 100% complete 
' [chain events] is colored in red

' [client authentication] starts 2021-10-11 and lasts 2 weeks and is 0% complete
'         note bottom
'             - depends on client onboarding
'             - in data transformer
'         end note

legend
**Legend**
*Blue line: today
*Green line: original deadline
*Yellow row: normal item
*Red row: additional scope
*Light green: extened scope
*Amound of background filled: % of task completed
end legend
@endgantt