version: '3.4'

services:
  transcomm_datagen_migration:
    build:
      context: ./
      dockerfile: ./docker/datagen/database-migration/Dockerfile
      args:
        DATABASE_URL: ${DATAGEN_DATABASE_URL}
    depends_on:
      db_mariadb:
        condition: service_healthy
  db_mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: 'always'
    ports:
      - '3306:3306'
    volumes:
      - type: volume
        source: mariadb-volume-data
        target: /var/lib/mysql/
    healthcheck:
      test: '/usr/bin/mysql --user=mila --password=Pas5word --execute "SHOW DATABASES;"'
      interval: 1s
      retries: 100
      start_period: 1s
      timeout: 10s
    environment:
      MYSQL_ROOT_PASSWORD: 'Pas5word'
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'mila'
      MYSQL_PASSWORD: 'Pas5word'

volumes:
  mariadb-volume-data:
